#Compilar con: make
#Ejecutar con: make run
#Limpiar con: make clean

CC = g++
CFLAGS = -Wall -g -std=c++17

p2_execute: p2_main.cc
	$(CC) $(CFLAGS) -o p2_execute p2_main_rp.cc
	
clean:
	rm -f *.o p2_execute